// Used-box references from Chrome for the shared Grid formatter.
import fs from 'node:fs';
import {browserLayoutFont, loadBrowserLayoutFont} from './browser_layout_font.mjs';
import path from 'node:path';
import {fileURLToPath, pathToFileURL} from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const moduleName = process.env.MUFFIN_PLAYWRIGHT_MODULE;
const {chromium} = await import(moduleName ? pathToFileURL(path.resolve(moduleName)).href : 'playwright');
const browser = await chromium.launch({headless: true, ...(process.env.CHROME_EXECUTABLE ? {executablePath: process.env.CHROME_EXECUTABLE} : {})});
const attribute = value => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;');
const cases = [
  {id:'max-content-glyph-overhang',html:'<div id="case" style="display:grid;font:italic 16px Arial;line-height:20px;width:200px;grid-template-columns:max-content 1fr"><div id="a">f</div><div id="b">X</div></div>'},
  {"id": "image-small-auto-min", "html": "<div id=\"case\" style=\"display:grid;width:140px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-small-zero-min", "html": "<div id=\"case\" style=\"display:grid;width:140px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"min-width:0\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-grow", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"flex:1;min-width:0\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-explicit-stretch", "html": "<div id=\"case\" style=\"display:grid;width:300px;height:140px;align-items:stretch;justify-items:stretch;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-transferred-size", "html": "<div id=\"case\" style=\"display:grid;width:140px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"height:40px\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-percent-padding-image", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"width:80px;padding:5%\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-percent-height-image", "html": "<div id=\"case\" style=\"display:grid;width:300px;height:200px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"height:50%\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-auto-ratio-border", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"width:100px;padding:10px;border:2px solid black;box-sizing:border-box;aspect-ratio:auto 1\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},

  {"id": "image-natural", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-width", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"width:80px\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-height", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"height:40px\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-max-width", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"max-width:80px\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-min-width", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"min-width:230px\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-max-height", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"max-height:40px\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-min-height", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"min-height:140px\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-ratio", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"aspect-ratio:1\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-auto-ratio", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"aspect-ratio:auto 1\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-percent", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"width:50%\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-constraints", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"max-width:80px;min-height:70px\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-box-content", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"width:100px;padding:10px;border:2px solid black\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-box-border", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"width:100px;padding:10px;border:2px solid black;box-sizing:border-box\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "image-ratio-border", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><img id=\"a\" src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMTAwIj48cmVjdCB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0icmVkIi8+PC9zdmc+\" style=\"width:100px;aspect-ratio:1;padding:10px;border:2px solid black;box-sizing:border-box\"><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "ratio-box", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><div id=\"a\" style=\"width:100px;aspect-ratio:2\"></div><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "ratio-stretch", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><div id=\"a\" style=\"aspect-ratio:2\"></div><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "ratio-cross-size", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><div id=\"a\" style=\"height:40px;aspect-ratio:2\"></div><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},
  {"id": "ratio-min", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px\"><div id=\"a\" style=\"width:80px;aspect-ratio:2;min-height:70px\"></div><div id=\"b\" style=\"width:50px;height:30px;flex-shrink:0\"></div></div>"},

  {id:'fit-content-cap', container:'width:300px;grid-template-columns:fit-content(90px) 1fr;gap:10px',children:['','height:30px'],texts:['alpha beta gamma delta','']},
  {id:'fit-content-minimum', container:'width:180px;grid-template-columns:fit-content(20px) 1fr;gap:10px',children:['','height:30px'],texts:['WWWWWWWWWW','']},
  {id:'fit-content-percent', container:'width:300px;grid-template-columns:fit-content(25%) 1fr;gap:10px',children:['','height:30px'],texts:['alpha beta gamma delta','']},
  {id:'subgrid-columns',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr 50px;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid"><div id="c" style="height:20px"></div><div id="d" style="height:30px"></div><div id="e" style="height:40px"></div></div></div>'},
  {id:'subgrid-partial',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr 50px;gap:10px"><div id="a" style="display:grid;grid-column:2/-1;grid-template-columns:subgrid"><div id="c" style="height:20px"></div><div id="d" style="height:30px"></div></div><div id="b" style="grid-column:1;grid-row:1;height:40px"></div></div>'},
  {id:'subgrid-both',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;grid-template-rows:30px 50px;gap:10px"><div id="a" style="display:grid;grid-area:1/1/3/3;grid-template-columns:subgrid;grid-template-rows:subgrid"><div id="c" style="">A</div><div id="d" style="grid-area:2/2">B</div></div></div>'},
  {id:'subgrid-rows',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:100px 1fr;grid-template-rows:30px 50px;gap:10px"><div id="a" style="display:grid;grid-row:1/-1;grid-template-columns:1fr;grid-template-rows:subgrid"><div id="c" style="">A</div><div id="d" style="">B</div></div></div>'},
  {id:'subgrid-padding',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;grid-template-rows:30px 50px;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid;padding:8px;border:2px solid black;"><div id="c" style="height:20px"></div><div id="d" style="height:30px"></div></div></div>'},
  {id:'subgrid-gap-zero',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;grid-template-rows:30px 50px;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid;column-gap:0;"><div id="c" style="height:20px"></div><div id="d" style="height:30px"></div></div></div>'},
  {id:'subgrid-gap-large',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;grid-template-rows:30px 50px;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid;column-gap:30px;padding:5px;"><div id="c" style="height:20px"></div><div id="d" style="height:30px"></div></div></div>'},
  {id:'subgrid-row-gap',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;grid-template-rows:30px 50px;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-row:1/-1;grid-template-rows:subgrid;grid-template-columns:subgrid;gap:0;padding:5px;"><div id="c" style=""></div><div id="d" style="grid-area:2/2"></div></div></div>'},
  {id:'subgrid-parent-names',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:[Left]80px[Middle]1fr[Right];gap:10px"><div id="a" style="display:grid;grid-column:Left/Right;grid-template-columns:subgrid"><div id="c" style="grid-column:Middle/Right;height:20px"></div><div id="d" style="grid-column:Left/Middle;height:30px"></div></div></div>'},
  {id:'subgrid-local-names',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid [A][B][C]"><div id="c" style="grid-column:B/C;height:20px"></div><div id="d" style="grid-column:A/B;height:30px"></div></div></div>'},
  {id:'subgrid-clamp',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid"><div id="c" style="grid-column:8/12;height:20px"></div><div id="d" style="grid-column:-9/-7;height:30px"></div><div id="e" style="grid-column:span 8;height:10px"></div></div></div>'},
  {id:'subgrid-auto-columns',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:auto 1fr;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid"><div id="c" style="">alpha beta gamma</div><div id="d" style="">B</div></div><div id="b" style="grid-column:1">x</div></div>'},
  {id:'subgrid-auto-padding',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:min-content 1fr;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid;padding:8px;border:2px solid black"><div id="c" style="">alpha beta gamma</div><div id="d" style="">B</div></div></div>'},
  {id:'subgrid-auto-rows',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:100px 1fr;grid-template-rows:auto auto;gap:10px"><div id="a" style="display:grid;grid-row:1/-1;grid-template-rows:subgrid;grid-template-columns:1fr"><div id="c" style="height:40px"></div><div id="d" style="height:70px"></div></div><div id="b" style="grid-column:2;grid-row:2;height:20px"></div></div>'},
  {id:'subgrid-both-intrinsic',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:auto 1fr;grid-template-rows:auto auto;gap:10px"><div id="a" style="display:grid;grid-area:1/1/3/3;grid-template-rows:subgrid;grid-template-columns:subgrid"><div id="c" style="">alpha beta</div><div id="d" style="grid-area:2/2">alpha beta gamma delta epsilon zeta eta theta</div></div></div>'},
  {id:'nested-grid-intrinsic',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:min-content 1fr;gap:10px"><div id="a" style="display:grid;grid-template-columns:80px 50px;gap:10px"><div id="c" style="height:20px"></div><div id="d" style="height:30px"></div></div><div id="b" style="height:40px"></div></div>'},
  {id:'nested-grid-fr-intrinsic',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:max-content 1fr;gap:10px"><div id="a" style="display:grid;grid-template-columns:1fr 2fr;gap:10px"><div id="c" style="">alpha beta</div><div id="d" style="">x</div></div><div id="b" style="height:40px"></div></div>'},
  {id:'nested-grid-spanning-intrinsic',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:400px;grid-template-columns:max-content 1fr;gap:10px"><div id="a" style="display:grid;grid-template-columns:1fr 2fr;gap:10px"><div id="c" style="grid-column:span 2">alpha beta gamma delta epsilon</div><div id="d" style="height:20px"></div><div id="e" style="height:30px"></div></div><div id="b" style="height:40px"></div></div>'},
  {id:'subgrid-deep',html:'<div id="case" style="display:grid;width:300px;grid-template-columns:80px 1fr 50px;gap:10px;font:16px Arial;line-height:20px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid;padding:5px"><div id="b" style="display:grid;grid-column:2/-1;grid-template-columns:subgrid"><div id="c" style="height:20px"></div><div id="d" style="height:30px"></div></div></div></div>'},
  {id:'subgrid-name-repeat-0',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid repeat(2,[Cell]) [End]"><div id="c" style="grid-column:Cell 2;height:20px"></div><div id="d" style="grid-column:Cell 1;height:30px"></div></div></div>'},
  {id:'subgrid-name-repeat-390',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid repeat(auto-fill,[Cell])"><div id="c" style="grid-column:Cell 2;height:20px"></div><div id="d" style="grid-column:Cell 1;height:30px"></div></div></div>'},
  {id:'subgrid-name-repeat-784',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid [Before] repeat(auto-fill,[Cell]) [End]"><div id="c" style="grid-column:Cell 2;height:20px"></div><div id="d" style="grid-column:Cell 1;height:30px"></div></div></div>'},
  {id:'subgrid-span-fr-minimum',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:140px;grid-template-columns:1fr 1fr;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid"><div id="c" style="grid-column:span 2">WWWWWWWWWWWWWWWW</div></div></div>'},
  {id:'subgrid-ignored-sizing',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;grid-template-rows:30px 50px;gap:10px"><div id="a" style="display:grid;grid-area:1/1/3/3;grid-template-columns:subgrid;grid-template-rows:subgrid;width:40px;height:10px;max-width:50px;justify-self:end;align-self:center"><div id="c" style=""></div><div id="d" style="grid-area:2/2"></div></div></div>'},
  {id:'subgrid-auto-row-padding',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:100px 1fr;grid-template-rows:auto auto;gap:10px"><div id="a" style="display:grid;grid-row:1/-1;grid-template-rows:subgrid;grid-template-columns:1fr;padding:8px;border:2px solid black"><div id="c" style="height:40px"></div><div id="d" style="height:70px"></div></div></div>'},
  {id:'subgrid-auto-row-gap',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:100px 1fr;grid-template-rows:auto auto;gap:10px"><div id="a" style="display:grid;grid-row:1/-1;grid-template-rows:subgrid;grid-template-columns:1fr;row-gap:30px"><div id="c" style="height:40px"></div><div id="d" style="height:70px"></div></div></div>'},
  {id:'subgrid-row-clamp',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:100px 1fr;grid-template-rows:30px 50px;gap:10px"><div id="a" style="display:grid;grid-row:1/-1;grid-template-rows:subgrid;grid-template-columns:1fr"><div id="c" style="grid-row:9/12"></div><div id="d" style="grid-row:-9/-7"></div><div id="e" style="grid-row:span 9"></div></div></div>'},
  {id:'subgrid-percent-padding',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid;padding:5%"><div id="c" style="height:20px"></div><div id="d" style="height:30px"></div></div></div>'},
  {id:'subgrid-auto-gap-zero',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:min-content 1fr;gap:20px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid;column-gap:0"><div id="c" style="">alpha beta gamma</div><div id="d" style="">B</div></div></div>'},
  {id:'subgrid-auto-gap-large',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:min-content 1fr;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid;column-gap:30px"><div id="c" style="">alpha beta gamma</div><div id="d" style="">B</div></div></div>'},
  {id:'subgrid-auto-margin',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;gap:10px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid;margin:5px"><div id="c" style="height:20px"></div><div id="d" style="height:30px"></div></div></div>'},
  {id:'subgrid-auto-row-fr',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:100px 1fr;grid-template-rows:1fr 2fr;gap:10px"><div id="a" style="display:grid;grid-row:1/-1;grid-template-rows:subgrid;grid-template-columns:1fr"><div id="c" style="height:40px"></div><div id="d" style="height:70px"></div></div></div>'},
  {id:'intrinsic-fit-content-nested',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:max-content 1fr;gap:10px"><div id="a" style="display:grid;grid-template-columns:fit-content(70px) 1fr;gap:10px"><div id="c" style="">alpha beta gamma delta</div><div id="d" style="">X</div></div></div>'},
  {id:'intrinsic-percent-nested',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:max-content 1fr;gap:10px"><div id="a" style="display:grid;grid-template-columns:50% auto;gap:10px"><div id="c" style="">alpha beta</div><div id="d" style="">X</div></div></div>'},
  {id:'intrinsic-minmax-nested',html:'<div id="case" style="display:grid;font:16px Arial;line-height:20px;width:400px;grid-template-columns:max-content 1fr;gap:10px"><div id="a" style="display:grid;grid-template-columns:minmax(min-content,70px) max-content;gap:10px"><div id="c" style="">alpha beta gamma delta</div><div id="d" style="">X</div></div></div>'},
  {id:'subgrid-deep-intrinsic',html:'<div id="case" style="display:grid;width:300px;grid-template-columns:min-content 1fr;gap:10px;font:16px Arial;line-height:20px"><div id="a" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid;padding:5px"><div id="b" style="display:grid;grid-column:1/-1;grid-template-columns:subgrid;padding:3px"><div id="c">alpha beta gamma</div><div id="d" style="height:30px"></div></div></div></div>'},
  {id:'subgrid-without-parent',container:'width:300px;grid-template-columns:subgrid;gap:10px',children:['height:20px','height:30px']},
  {id:'minmax-intrinsic-floor',container:'width:300px;grid-template-columns:minmax(min-content,20px) 1fr;gap:10px',children:['','height:30px'],texts:['alpha beta gamma','']},
  {id:'minmax-max-content-floor',container:'width:300px;grid-template-columns:minmax(max-content,20px) 1fr;gap:10px',children:['','height:30px'],texts:['alpha beta gamma','']},
  {id:'minmax-auto-cap',container:'width:300px;grid-template-columns:minmax(auto,20px) 1fr;gap:10px',children:['','height:30px'],texts:['alpha beta gamma','']},
  {id:'indefinite-row-partial-fr',container:'width:200px;grid-template-rows:.25fr .25fr;gap:10px',children:['height:20px','height:30px']},
  {id:'indefinite-row-mixed-fr',container:'width:200px;grid-template-rows:.5fr 2fr;gap:10px',children:['height:20px','height:30px']},
  {id:'fit-content-spanning',container:'width:300px;grid-template-columns:fit-content(70px) fit-content(90px) 1fr;gap:10px',children:['grid-column:span 2','height:30px','height:20px'],texts:['alpha beta gamma delta epsilon','','']},
  {"id": "subgrid-local-areas", "html": "<div id=\"case\" style=\"display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;gap:10px;\"><div id=\"a\" style=\"display:grid;grid-column:1/-1;grid-template-columns:subgrid;grid-template-areas:'Left Right'\"><div id=\"c\" style=\"grid-area:Right;height:20px\"></div><div id=\"d\" style=\"grid-area:Left;height:30px\"></div></div></div>"},
  {"id": "subgrid-inherited-areas", "html": "<div id=\"case\" style=\"display:grid;font:16px Arial;line-height:20px;width:300px;grid-template-columns:80px 1fr;gap:10px;grid-template-areas:'Left Right'\"><div id=\"a\" style=\"display:grid;grid-column:1/-1;grid-template-columns:subgrid;\"><div id=\"c\" style=\"grid-area:Right;height:20px\"></div><div id=\"d\" style=\"grid-area:Left;height:30px\"></div></div></div>"},
  {"id": "subgrid-column-flow", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:80px 1fr;grid-template-rows:30px 50px;gap:10px;font:16px Arial;line-height:20px\"><div id=\"a\" style=\"display:grid;grid-area:1/1/3/3;grid-template-columns:subgrid;grid-template-rows:subgrid;grid-auto-flow:column\"><div id=\"c\"></div><div id=\"d\"></div><div id=\"e\"></div><div id=\"f\"></div></div></div>"},
  {id:'cyclic-rows',container:'width:300px;grid-template-columns:1fr;grid-template-rows:50% 50%',children:['',''],texts:['A','A<br>B<br>C']},
  {id:'cyclic-calc-rows',container:'width:300px;grid-template-columns:1fr;grid-template-rows:calc(50% + 10px) auto',children:['',''],texts:['A','A<br>B<br>C']},
  {id:'cyclic-row-gap',container:'width:300px;grid-template-columns:1fr;grid-template-rows:20px 40px;row-gap:20%',children:['',''],texts:['A','A<br>B<br>C']},
  {id:'cyclic-calc-gap',container:'width:300px;grid-template-columns:1fr;grid-template-rows:auto auto;row-gap:calc(20% + 10px)',children:['',''],texts:['A','A<br>B<br>C']},
  {id:'cyclic-percent-fr',container:'width:300px;grid-template-columns:1fr;grid-template-rows:50% 1fr',children:['',''],texts:['A','A<br>B<br>C']},
  {id:'cyclic-row-padding',container:'width:300px;grid-template-columns:1fr;grid-template-rows:50% auto;padding:10px;border:2px solid black',children:['',''],texts:['A','A<br>B<br>C']},
  {id:'cyclic-min-height',container:'width:300px;grid-template-columns:1fr;grid-template-rows:50% auto;min-height:150px',children:['',''],texts:['A','A<br>B<br>C']},
  {id:'cyclic-max-height',container:'width:300px;grid-template-columns:1fr;grid-template-rows:50% auto;max-height:40px',children:['',''],texts:['A','A<br>B<br>C']},
  {id:'cyclic-implicit-rows',container:'width:300px;grid-template-columns:1fr;grid-auto-rows:50%',children:['',''],texts:['A','A<br>B<br>C']},
  {id:'definite-percent-height-min',container:'width:300px;grid-template-columns:1fr;height:100px;min-height:150px;grid-template-rows:50% 50%',children:['',''],texts:['A','A<br>B<br>C']},
  {id:'definite-percent-height-max',container:'width:300px;grid-template-columns:1fr;height:150px;max-height:100px;grid-template-rows:50% 50%',children:['',''],texts:['A','A<br>B<br>C']},
  {"id": "cyclic-nested-columns", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:max-content 1fr;font:16px Arial;line-height:20px\"><div id=\"a\" style=\"display:grid;grid-template-columns:50% auto\"><div id=\"c\">alpha beta</div><div id=\"d\">B</div></div><div id=\"b\" style=\"height:20px\"></div></div>"},
  {"id": "cyclic-nested-calc", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:max-content 1fr;font:16px Arial;line-height:20px\"><div id=\"a\" style=\"display:grid;grid-template-columns:calc(50% + 10px) auto\"><div id=\"c\">alpha beta</div><div id=\"d\">B</div></div><div id=\"b\" style=\"height:20px\"></div></div>"},
  {"id": "cyclic-nested-gap", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:max-content 1fr;font:16px Arial;line-height:20px\"><div id=\"a\" style=\"display:grid;grid-template-columns:auto auto;column-gap:20%\"><div id=\"c\">alpha beta</div><div id=\"d\">B</div></div><div id=\"b\" style=\"height:20px\"></div></div>"},
  {"id": "cyclic-nested-calc-gap", "html": "<div id=\"case\" style=\"display:grid;width:300px;grid-template-columns:max-content 1fr;font:16px Arial;line-height:20px\"><div id=\"a\" style=\"display:grid;grid-template-columns:auto auto;column-gap:calc(20% + 10px)\"><div id=\"c\">alpha beta</div><div id=\"d\">B</div></div><div id=\"b\" style=\"height:20px\"></div></div>"},
  {"id": "repeat-rows-minimum-auto-fill", "container": "width:300px;grid-template-rows:repeat(auto-fill,100px);gap:10px;min-height:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-rows-minimum-auto-fit", "container": "width:300px;grid-template-rows:repeat(auto-fit,100px);gap:10px;min-height:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-rows-maximum-auto-fill", "container": "width:300px;grid-template-rows:repeat(auto-fill,100px);gap:10px;max-height:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-rows-maximum-auto-fit", "container": "width:300px;grid-template-rows:repeat(auto-fit,100px);gap:10px;max-height:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-rows-both-auto-fill", "container": "width:300px;grid-template-rows:repeat(auto-fill,100px);gap:10px;min-height:250px;max-height:350px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-rows-both-auto-fit", "container": "width:300px;grid-template-rows:repeat(auto-fit,100px);gap:10px;min-height:250px;max-height:350px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-rows-conflict-auto-fill", "container": "width:300px;grid-template-rows:repeat(auto-fill,100px);gap:10px;min-height:350px;max-height:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-rows-conflict-auto-fit", "container": "width:300px;grid-template-rows:repeat(auto-fit,100px);gap:10px;min-height:350px;max-height:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-rows-padding-auto-fill", "container": "width:300px;grid-template-rows:repeat(auto-fill,100px);gap:10px;min-height:250px;padding:10px;border:2px solid black;box-sizing:border-box", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-rows-padding-auto-fit", "container": "width:300px;grid-template-rows:repeat(auto-fit,100px);gap:10px;min-height:250px;padding:10px;border:2px solid black;box-sizing:border-box", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-columns-minimum-auto-fill", "container": "width:max-content;grid-template-columns:repeat(auto-fill,100px);gap:10px;min-width:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-columns-minimum-auto-fit", "container": "width:max-content;grid-template-columns:repeat(auto-fit,100px);gap:10px;min-width:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-columns-maximum-auto-fill", "container": "width:max-content;grid-template-columns:repeat(auto-fill,100px);gap:10px;max-width:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-columns-maximum-auto-fit", "container": "width:max-content;grid-template-columns:repeat(auto-fit,100px);gap:10px;max-width:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-columns-both-auto-fill", "container": "width:max-content;grid-template-columns:repeat(auto-fill,100px);gap:10px;min-width:250px;max-width:350px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-columns-both-auto-fit", "container": "width:max-content;grid-template-columns:repeat(auto-fit,100px);gap:10px;min-width:250px;max-width:350px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-columns-conflict-auto-fill", "container": "width:max-content;grid-template-columns:repeat(auto-fill,100px);gap:10px;min-width:350px;max-width:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-columns-conflict-auto-fit", "container": "width:max-content;grid-template-columns:repeat(auto-fit,100px);gap:10px;min-width:350px;max-width:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-columns-padding-auto-fill", "container": "width:max-content;grid-template-columns:repeat(auto-fill,100px);gap:10px;min-width:250px;padding:10px;border:2px solid black;box-sizing:border-box", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-columns-padding-auto-fit", "container": "width:max-content;grid-template-columns:repeat(auto-fit,100px);gap:10px;min-width:250px;padding:10px;border:2px solid black;box-sizing:border-box", "children": ["height:20px", "height:30px"]},
  {"id": "percent-height-auto-rows", "container": "width:300px;grid-template-columns:1fr;", "children": ["height:50%", "height:calc(50% + 10px)"], "texts": ["A", "B"]},
  {"id": "percent-padding-auto-rows", "container": "width:300px;grid-template-columns:1fr;", "children": ["padding:10%", "padding:calc(10% + 5px)"], "texts": ["A", "B"]},
  {"id": "percent-row-minmax", "container": "width:300px;grid-template-columns:1fr;grid-template-rows:minmax(50%,1fr) auto;", "children": ["height:20px", "height:60px"], "texts": ["A", "B"]},
  {"id": "repeat-minimum-calc", "container": "width:300px;grid-template-rows:repeat(auto-fill,100px);gap:10px;min-height:calc(100px + 150px)", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-max-percent", "container": "width:300px;grid-template-rows:repeat(auto-fill,100px);gap:10px;max-height:50%", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-min-percent", "container": "width:300px;grid-template-rows:repeat(auto-fill,100px);gap:10px;min-height:50%", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-minimum-pattern", "container": "width:300px;grid-template-rows:repeat(auto-fill,60px 80px);gap:10px;min-height:250px", "children": ["height:20px", "height:30px"]},
  {"id": "repeat-minimum-exact", "container": "width:300px;grid-template-rows:repeat(auto-fill,100px);gap:10px;min-height:210px", "children": ["height:20px", "height:30px"]},
  {id:'auto-fill', container:'width:500px;grid-template-columns:repeat(auto-fill,minmax(100px,1fr));gap:10px', children:['height:20px','height:30px']},
  {id:'auto-fit', container:'width:500px;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));gap:10px', children:['height:20px','height:30px']},
  {id:'auto-fit-empty', container:'width:500px;grid-template-columns:repeat(auto-fit,100px);gap:10px', children:[]},
  {id:'auto-fit-hole', container:'width:500px;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));gap:10px', children:['grid-column:1;height:20px','grid-column:3;height:30px']},
  {id:'auto-fit-span', container:'width:500px;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));gap:10px', children:['grid-column:span 2;height:20px','height:30px']},
  {id:'auto-fit-last-line', container:'width:500px;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));gap:10px', children:['grid-column:-2/-1;height:30px']},
  {id:'auto-fit-center', container:'width:500px;grid-template-columns:repeat(auto-fit,100px);justify-content:center;gap:10px', children:['grid-column:1;height:20px','grid-column:3;height:30px']},
  {id:'auto-fit-space-between', container:'width:500px;grid-template-columns:repeat(auto-fit,100px);justify-content:space-between;gap:10px', children:['grid-column:1;height:20px','grid-column:3;height:30px']},
  {id:'auto-fit-pattern', container:'width:500px;grid-template-columns:repeat(auto-fit,60px 80px);gap:10px', children:['grid-column:1;height:20px','grid-column:4;height:30px']},
  {id:'auto-fit-fixed-siblings', container:'width:500px;grid-template-columns:[Begin] 50px [Before] repeat(auto-fit,[Cell] minmax(80px,1fr) [EndCell]) [After] 40px [Finish];gap:10px', children:['grid-column:Before/EndCell;height:20px','grid-column:After/Finish;height:30px']},
  {id:'auto-fill-pattern', container:'width:500px;grid-template-columns:repeat(auto-fill,60px 80px);gap:10px', children:['height:20px','height:30px','height:40px']},
  {id:'auto-fill-percent', container:'width:500px;grid-template-columns:repeat(auto-fill,minmax(20%,1fr));column-gap:2%', children:['height:20px','height:30px']},
  {id:'auto-fill-calc', container:'width:500px;grid-template-columns:repeat(auto-fill,minmax(calc(25% - 10px),1fr));gap:10px', children:['height:20px','height:30px']},
  {id:'auto-fill-max-bound', container:'width:500px;grid-template-columns:repeat(auto-fill,minmax(60px,100px));gap:10px', children:['height:20px','height:30px']},
  {id:'auto-fit-hidden-item', container:'width:500px;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));gap:10px', children:['height:20px','display:none','height:30px']},
  {id:'auto-fit-narrow', container:'width:80px;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));gap:10px', children:['height:20px','height:30px']},
  {id:'auto-fit-rows', container:'width:100px;height:300px;grid-template-rows:repeat(auto-fit,minmax(60px,1fr));grid-auto-flow:column;gap:10px', children:['','']},
  {id:'auto-fill-indefinite-rows', container:'width:100px;grid-template-rows:repeat(auto-fill,40px);gap:10px', children:['height:20px','height:30px']},
  {id:'responsive-fit-wide', viewportWidth:500, container:'width:100%;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px', children:['height:20px','height:30px','height:40px']},
  {id:'responsive-fit-narrow', viewportWidth:300, container:'width:100%;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px', children:['height:20px','height:30px','height:40px']},
  {id:'named-lines', container:'width:300px;grid-template-columns:[Left]80px[Middle]1fr[Right];gap:10px', children:['grid-column:Middle/Right;height:30px','grid-column:Left/Middle;height:20px']},
  {id:'named-repeat', container:'width:300px;grid-template-columns:repeat(3,[Col]1fr[End]);gap:10px', children:['grid-column:Col 2/End 3;height:20px','grid-column:Col -3/End -3;height:30px']},
  {id:'named-span', container:'width:300px;grid-template-columns:[Col]1fr[Col]1fr[Col]1fr[End];gap:10px', children:['grid-column:Col/span 2 Col;height:20px','grid-column:span 2 Col/End;height:30px']},
  {id:'named-implicit', container:'width:300px;grid-template-columns:[Start]100px[End];grid-auto-columns:40px;gap:10px', children:['grid-column:Missing;height:20px','grid-column:Missing -1;height:30px']},
  {id:'named-case', container:'width:300px;grid-template-columns:[A]60px[a]80px[End];gap:10px', children:['grid-column:a/End;height:20px','grid-column:A/a;height:30px']},
  {id:'named-auto-repeat', container:'width:500px;grid-template-columns:repeat(auto-fill,[Cell]100px[End]);gap:10px', children:['grid-column:Cell 2/End 3;height:20px','grid-column:Cell -1/End -1;height:30px']},
  {id:'template-areas', container:'width:300px;grid-template-columns:80px 1fr;grid-template-rows:30px 50px;grid-template-areas:"Header Header" "Side Main";gap:10px', children:['grid-area:Main','grid-area:Header','grid-area:Side']},
  {id:'areas-implicit-tracks', container:'width:300px;grid-template-areas:"Title Title" "Left Right";grid-auto-columns:80px 1fr;grid-auto-rows:30px 40px;gap:10px', children:['grid-area:Right','grid-area:Title','grid-area:Left']},
  {id:'areas-holes', container:'width:300px;grid-template-columns:1fr 1fr;grid-template-areas:"Title Title" ". Main";gap:10px', children:['grid-area:Title;height:20px','grid-area:Main;height:30px','height:40px']},
  {id:'area-lines', container:'width:300px;grid-template-columns:80px 1fr;grid-template-rows:30px 50px;grid-template-areas:"Top Top" "Left Main";gap:10px', children:['grid-column:Main-start/Main-end;grid-row:Main-start/Main-end','grid-column:Top;grid-row:Top']},
  {id:'area-case', container:'width:300px;grid-template-columns:1fr 2fr;grid-template-areas:"A a";gap:10px', children:['grid-area:a;height:30px','grid-area:A;height:20px']},
  {id:'auto-fit-area', container:'width:500px;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));grid-template-areas:"Main Main . .";gap:10px', children:['grid-area:Main;height:20px']},
  {id:'area-repeat-boundaries', container:'width:300px;grid-template-columns:repeat(3,[Cell]1fr[End]);grid-template-areas:"Title Title Title" "Left Main Main";gap:10px', children:['grid-area:Main;height:30px','grid-column:Cell/End 3;grid-row:Title;height:20px','grid-area:Left;height:40px']},
  {id:'fr-gap', container:'width:320px;grid-template-columns:1fr 2fr;gap:10px', children:['height:30px','height:40px']},
  {id:'fixed-auto-rows', container:'width:300px;grid-template-columns:100px 80px;gap:10px', children:['height:30px','height:40px','height:20px']},
  {id:'spans', container:'width:300px;grid-template-columns:repeat(3,1fr);gap:10px', children:['grid-column:span 2;grid-row:span 2;height:80px','height:20px','height:30px','height:25px']},
  {id:'explicit-overlap', container:'width:300px;grid-template-columns:repeat(3,1fr);grid-template-rows:30px 40px;gap:10px', children:['grid-area:1/1/3/3','grid-column:2/4;grid-row:1','height:10px']},
  {id:'sparse', container:'width:300px;grid-template-columns:repeat(3,1fr);gap:10px', children:['grid-column:span 2;height:20px','grid-column:span 2;height:30px','height:10px']},
  {id:'dense', container:'width:300px;grid-template-columns:repeat(3,1fr);grid-auto-flow:row dense;gap:10px', children:['grid-column:span 2;height:20px','grid-column:span 2;height:30px','height:10px']},
  {id:'column-flow', container:'width:300px;grid-template-rows:30px 40px;grid-auto-flow:column;gap:10px', children:['','height:20px','','']},
  {id:'negative-lines', container:'width:300px;grid-template-columns:80px 1fr;gap:10px', children:['grid-column:1/-1;height:20px','grid-column:-2;height:30px']},
  {id:'implicit-before', container:'width:300px;grid-template-columns:100px 100px;grid-auto-columns:40px;gap:10px', children:['grid-column:-4/-3;height:20px','height:30px']},
  {id:'implicit-pattern', container:'width:300px;grid-template-columns:100px;grid-auto-columns:30px 50px;grid-auto-rows:20px 40px;gap:5px', children:['grid-column:3','grid-column:2;grid-row:2','grid-row:3']},
  {id:'percent-calc', container:'width:300px;grid-template-columns:25% calc(50% - 10px) 1fr;gap:5px', children:['height:20px','height:30px','height:10px']},
  {id:'intrinsic', container:'width:300px;grid-template-columns:min-content max-content;gap:10px', children:['',''], texts:['alpha beta','alpha beta']},
  {id:'automatic-minimum', container:'width:140px;grid-template-columns:1fr 1fr', children:['',''], texts:['WWWWWWWWWWWWWWWW','x']},
  {id:'zero-track-minimum', container:'width:140px;grid-template-columns:minmax(0,1fr) minmax(0,1fr)', children:['',''], texts:['WWWWWWWWWWWWWWWW','x']},
  {id:'hidden-minimum', container:'width:140px;grid-template-columns:1fr 1fr', children:['overflow:hidden',''], texts:['WWWWWWWWWWWWWWWW','x']},
  {id:'intrinsic-zero-item-min', container:'width:300px;grid-template-columns:min-content 1fr', children:['min-width:0',''], texts:['alpha beta','B']},
  {id:'row-hidden-minimum', container:'width:100px;height:60px;grid-template-rows:1fr 1fr', children:['overflow:hidden',''], texts:['A<br>A<br>A<br>A','B']},
  {id:'row-zero-minimum', container:'width:100px;height:60px;grid-template-rows:1fr 1fr', children:['min-height:0',''], texts:['A<br>A<br>A<br>A','B']},
  {id:'minmax', container:'width:300px;grid-template-columns:minmax(50px,100px) 1fr;gap:10px', children:['height:20px','height:30px']},
  {id:'text-reflow', container:'width:200px;grid-template-columns:1fr 50px;gap:10px', children:['min-width:0',''], texts:['alpha beta gamma delta epsilon zeta','B']},
  {id:'item-alignment', container:'width:300px;height:120px;grid-template-columns:1fr 1fr;place-items:center end', children:['width:30px;height:20px','width:40px;height:30px;place-self:end start']},
  {id:'content-alignment', container:'width:300px;height:150px;grid-template-columns:60px 80px;grid-template-rows:30px 40px;justify-content:space-between;align-content:center;gap:10px', children:['','','','']},
  {id:'auto-margins', container:'width:300px;height:100px;grid-template-columns:1fr 1fr;gap:10px', children:['width:30px;height:20px;margin:auto','width:40px;height:30px;margin-left:auto;margin-top:auto']},
  {id:'percent-padding', container:'width:300px;grid-template-columns:1fr 2fr;gap:10px', children:['padding:10%;border:2px solid black','padding:5%'], texts:['alpha beta','B']},
  {id:'border-box', container:'width:300px;box-sizing:border-box;padding:10px;border:2px solid black;grid-template-columns:1fr 1fr;gap:10px', children:['height:40px;padding:5px;border:2px solid red;box-sizing:border-box','height:30px']},
  {id:'item-constraints', container:'width:300px;grid-template-columns:1fr 1fr;gap:10px', children:['max-width:80px;min-height:40px','min-width:170px;height:20px'], texts:['alpha beta gamma','B']},
  {id:'row-fr', container:'width:200px;height:200px;grid-template-columns:1fr;grid-template-rows:1fr 2fr;gap:10px', children:['','']},
  {id:'indefinite-row-fr', container:'width:200px;grid-template-columns:1fr;grid-template-rows:1fr 2fr;gap:10px', children:['height:20px','height:30px']},
  {id:'partial-fr', container:'width:300px;grid-template-columns:.25fr .25fr;gap:10px', children:['height:20px','height:30px']},
  {id:'auto-stretch', container:'width:300px;grid-template-columns:auto auto;gap:10px', children:['',''], texts:['alpha beta','B']},
  {id:'span-end', container:'width:300px;grid-template-columns:repeat(3,1fr);gap:10px', children:['grid-column:span 2/-1;height:20px','height:30px']},
  {id:'locked-rows', container:'width:300px;grid-template-columns:repeat(3,1fr);gap:10px', children:['grid-row:2;height:20px','grid-row:2;grid-column:span 2;height:30px','height:40px','height:10px']},
  {id:'locked-row-sparse', container:'width:300px;grid-template-columns:80px 80px 80px;grid-auto-columns:40px;gap:10px', children:['grid-column:2;grid-row:1;height:10px','grid-column:span 2;grid-row:1;height:20px','grid-row:1;height:30px']},
  {id:'locked-row-dense', container:'width:300px;grid-template-columns:80px 80px 80px;grid-auto-columns:40px;grid-auto-flow:row dense;gap:10px', children:['grid-column:2;grid-row:1;height:10px','grid-column:span 2;grid-row:1;height:20px','grid-row:1;height:30px']},
  {id:'spanning-text', container:'width:300px;grid-template-columns:auto auto;gap:10px', children:['grid-column:span 2','height:20px','height:30px'], texts:['alpha beta gamma delta epsilon','','']},
  {id:'percent-gap', container:'width:300px;grid-template-columns:1fr 1fr;column-gap:10%;row-gap:10%', children:['height:20px','height:30px','height:40px']},
  {id:'percent-height', container:'width:200px;height:200px;grid-template-columns:1fr;grid-template-rows:50% 1fr', children:['height:50%','']},
  {id:'display-none-order', container:'width:200px;grid-template-columns:1fr 1fr;gap:10px', children:['height:20px;order:2','display:none','height:30px;order:-1']},
  {id:'nested', html:'<div id="case" style="display:grid;width:300px;grid-template-columns:1fr 50px;gap:10px;font:16px Arial;line-height:20px"><div id="a" style="display:grid;grid-template-columns:1fr 2fr;gap:5px;min-width:0"><div id="c" style="height:20px"></div><div id="d" style="height:30px"></div></div><div id="b" style="height:40px"></div></div>'},
];
const imageSource = /src="([^"]+)"/.exec(cases.find(c => c.html?.includes('<img')).html)[1];
for (const [id, attributes] of [
  ['image-width-attribute', 'width="80"'],
  ['image-width-attribute-css-auto', 'width="80" style="width:auto"'],
]) cases.push({id, html:cases.find(c => c.id === 'image-natural').html.replace('style=""', attributes)});
for (const [id, image] of [
  ['image-ratio-degenerate', 'width:80px;aspect-ratio:0'],
  ['image-ratio-zero-denominator', 'width:80px;aspect-ratio:2/0'],
  ['image-max-height-padding', 'max-height:40px;padding:10px;border:2px solid black'],
  ['image-min-height-padding', 'min-height:120px;padding:10px;border:2px solid black'],
  ['image-max-height-border-box', 'max-height:64px;padding:10px;border:2px solid black;box-sizing:border-box'],
]) cases.push({id, html:cases.find(c => c.id === 'image-natural').html.replace('style=""', `style="${image}"`)});
for (const [id, rows, image, extra] of [
  ['image-stretch-fixed-row', '80px', 'align-self:stretch', ''],
  ['image-stretch-row-span', '40px 70px', 'align-self:stretch;grid-row:span 2', ''],
  ['image-stretch-fr-rows', '1fr 2fr', 'align-self:stretch;grid-row:span 2', 'height:150px'],
  ['image-stretch-row-max-width', '80px', 'align-self:stretch;max-width:120px', ''],
]) cases.push({id, html:`<div id="case" style="display:grid;width:300px;grid-template-columns:auto 50px;grid-template-rows:${rows};gap:10px;${extra}"><img id="a" src="${imageSource}" style="${image}"><div id="b" style="height:30px"></div></div>`});
try {
  cases.push(...JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/theme/wpt/cases.json'),'utf8')).cases.filter(c => c.kind === 'grid'));
  const page = await browser.newPage({viewport:{width:800,height:700}});
  const base = fs.readFileSync(path.join(root,'resources/themes/document-base.css'),'utf8');
  const font = browserLayoutFont(root);
  for (const c of cases) {
    const viewportWidth = c.viewportWidth ?? 800;
    await page.setViewportSize({width:viewportWidth,height:700});
    c.html ??= `<div id="case" style="${attribute(`display:grid;font:16px Arial;line-height:20px;${c.container}`)}">${c.children.map((style,i)=>`<div id="${'abcd'[i]}" style="${attribute(style)}">${c.texts?.[i] ?? ''}</div>`).join('')}</div>`;
    c.html = font.replace(c.html);
    await page.setContent(`<!doctype html><style>${base}\n${font.css}</style><div id="write" style="padding:0;width:${viewportWidth}px">${c.html}</div>`);
    await loadBrowserLayoutFont(page, font);
    const parsed = await page.evaluate(() => {
      const el = document.querySelector('#case');
      return {display:getComputedStyle(el).display, areas:el.style.gridTemplateAreas, columns:el.style.gridTemplateColumns};
    });
    if (parsed.display !== 'grid' || (c.container?.includes('grid-template-areas') && !parsed.areas) ||
        (c.container?.includes('grid-template-columns') && !parsed.columns)) {
      throw new Error(`${c.id}: browser did not parse the intended Grid declarations`);
    }
    if (await page.evaluate(() => document.compatMode) !== "CSS1Compat") throw new Error("Browser oracle must use standards mode");
    c.expected = await page.evaluate(()=>{
      const outer = document.querySelector('#case').getBoundingClientRect();
      return Object.fromEntries([...document.querySelectorAll('#case,#case [id]')].map(el=>{
        const r=el.getBoundingClientRect();return [el.id,{x:r.left-outer.left,y:r.top-outer.top,width:r.width,height:r.height}];
      }));
    });
    for (const [id, values] of Object.entries(c.assertions ?? {})) for (const [property, value] of Object.entries(values)) {
      if (Math.abs(c.expected[id][property] - value) > .05) throw new Error(`${c.id}: WPT ${id}.${property} assertion differs`);
    }
    if (c.html.includes('<img')) c.imageContent = await page.evaluate(() => {
      const image = document.querySelector('#case img');
      const rect = image.getBoundingClientRect(), outer = document.querySelector('#case').getBoundingClientRect();
      const style = getComputedStyle(image);
      const inset = side => parseFloat(style['padding' + side]) + parseFloat(style['border' + side + 'Width']);
      return {x:rect.left - outer.left + inset('Left'), y:rect.top - outer.top + inset('Top'),
              width:rect.width - inset('Left') - inset('Right'), height:rect.height - inset('Top') - inset('Bottom')};
    });
    delete c.container; delete c.children; delete c.texts;
  }
  fs.writeFileSync(process.argv[2] ?? path.join(root,'tests/fixtures/theme/grid-layout-browser.json'),JSON.stringify({browser:await browser.version(),font:font.metadata,cases},null,2)+'\n');
} finally { await browser.close(); }
