# All Muffin test executables, registered via muffin_add_test (see MuffinTestFunctions.cmake).
# One line per test; grouped by subsystem in build order. Included from the top-level
# CMakeLists.txt after MUFFIN_TEST_ENVIRONMENT_MODIFICATIONS is assembled.

include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/MuffinTestFunctions.cmake)

# --- perf benchmark (pure MuffinCore, no GUI lock; defaults are a fast smoke — override
#     MUFFIN_BENCH_SIZE_MB / MUFFIN_BENCH_ITERS for a real measurement run) ---
muffin_add_test(NAME MuffinTypingPerfBench SOURCE tests/perf/TypingPerfBench.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinOpenMemBench SOURCE tests/perf/OpenMemBench.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinOpenRenderMemBench SOURCE tests/perf/OpenRenderMemBench.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinLargeDocumentRoundTripTest SOURCE tests/perf/LargeDocumentRoundTripTest.cpp LINK MuffinUi EXTRA_SOURCES src/io/FileController.cpp RESOURCE_LOCK)
muffin_add_test(NAME MuffinThirdDashProbe SOURCE tests/perf/ThirdDashProbe.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinSplitAfterRuleProbe SOURCE tests/perf/SplitAfterRuleProbe.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinThematicBreakRangeProbe SOURCE tests/perf/ThematicBreakRangeProbe.cpp LINK MuffinUi RESOURCE_LOCK)

# --- parser / document (pure logic; link MuffinCore, no Qt GUI lock) ---
muffin_add_test(NAME MuffinMermaidCompatibilityTest SOURCE tests/mermaid/MermaidCompatibilityTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/preprocess-and-detect.json)
muffin_add_test(NAME MuffinMermaidFlowchartParserTest SOURCE tests/mermaid/MermaidFlowchartParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/flowchart-db.json)
muffin_add_test(NAME MuffinMermaidFlowchartDifferentialFuzzTest SOURCE tests/mermaid/MermaidFlowchartDifferentialFuzzTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/flowchart-differential-fuzz.json)
muffin_add_test(NAME MuffinMermaidParserErrorTest SOURCE tests/mermaid/MermaidParserErrorTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/flowchart-errors.json)
muffin_add_test(NAME MuffinMermaidSecurityTest SOURCE tests/mermaid/MermaidSecurityTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinMermaidFuzzTest SOURCE tests/mermaid/MermaidFuzzTest.cpp LINK MuffinCore)
set_tests_properties(MuffinMermaidFuzzTest PROPERTIES RUN_SERIAL TRUE)
muffin_add_test(NAME MuffinMermaidRenderCacheTest SOURCE tests/mermaid/MermaidRenderCacheTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSvgExportTest SOURCE tests/mermaid/MermaidSvgExportTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui Qt6::Svg RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidConfigEffectMatrixTest SOURCE tests/mermaid/MermaidConfigEffectMatrixTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/config-effect-matrix.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSceneCullingTest SOURCE tests/mermaid/MermaidSceneCullingTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderMermaidBlockTest SOURCE tests/render/RenderMermaidBlockTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowchartLayoutTest SOURCE tests/mermaid/MermaidFlowchartLayoutTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidDagreLayoutTest SOURCE tests/mermaid/MermaidDagreLayoutTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidDagreSnapshotTest SOURCE tests/mermaid/MermaidDagreSnapshotTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-geometry.json RESOURCE_LOCK)
# MuffinMermaidDagreLayoutTest (tests/mermaid/MermaidDagreLayoutTest.cpp) is the
# milestone-C acceptance gate for layoutFlowchartNodesDagre; temporarily
# registered while debugging the remaining cases (compound-crossing mirror,
# self-edge). Skips compound-crossing via pendingNative.
muffin_add_test(NAME MuffinMermaidGraphTest SOURCE tests/mermaid/MermaidGraphTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinMermaidShapeRegistryTest SOURCE tests/mermaid/MermaidShapeRegistryTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinMermaidThemeTest SOURCE tests/mermaid/MermaidThemeTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-theme.json)
muffin_add_test(NAME MuffinMermaidFlowStyleResolveTest SOURCE tests/mermaid/MermaidFlowStyleResolveTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-style-cascade.json)
muffin_add_test(NAME MuffinMermaidFlowchartSceneTest SOURCE tests/mermaid/MermaidFlowchartSceneTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-scene.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowchartAnimationTest SOURCE tests/mermaid/MermaidFlowchartAnimationTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidGoldenPixelTest SOURCE tests/mermaid/MermaidGoldenPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/golden-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowchartSvgStructuralTest SOURCE tests/mermaid/MermaidFlowchartSvgStructuralTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/golden-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowchartLabelOracleTest SOURCE tests/mermaid/MermaidFlowchartLabelOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-label.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowchartCoverageMatrixTest SOURCE tests/mermaid/MermaidFlowchartCoverageMatrixTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/flowchart-db.json)
muffin_add_test(NAME MuffinMermaidTextLayoutAuditTest SOURCE tests/mermaid/MermaidTextLayoutAuditTest.cpp LINK MuffinCore FIXTURE src/mermaid/flowchart/FlowLabel.cpp)
muffin_add_test(NAME MuffinMermaidRoughOpsTest SOURCE tests/mermaid/MermaidRoughOpsTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/rough-ops.json)
muffin_add_test(NAME MuffinMermaidSequenceParserTest SOURCE tests/mermaid/MermaidSequenceParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/sequence-db.json)
muffin_add_test(NAME MuffinMermaidClassParserTest SOURCE tests/mermaid/MermaidClassParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/class-db.json)
muffin_add_test(NAME MuffinMermaidErParserTest SOURCE tests/mermaid/MermaidErParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/er-db.json)
muffin_add_test(NAME MuffinMermaidStateUpstreamContractTest SOURCE tests/mermaid/MermaidStateUpstreamContractTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/state-db.json)
muffin_add_test(NAME MuffinMermaidStateDifferentialFuzzTest SOURCE tests/mermaid/MermaidStateDifferentialFuzzTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/state-differential-fuzz.json)
muffin_add_test(NAME MuffinMermaidStateSceneTest SOURCE tests/mermaid/MermaidStateSceneTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/state-db.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidStateLayoutOracleTest SOURCE tests/mermaid/MermaidStateLayoutOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/state-layout.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidStateLinkStyleTest SOURCE tests/mermaid/MermaidStateLinkStyleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidStateSvgStructuralTest SOURCE tests/mermaid/MermaidStateSvgStructuralTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/state-layout.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidStatePixelTest SOURCE tests/mermaid/MermaidStatePixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/state-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassDifferentialFuzzTest SOURCE tests/mermaid/MermaidClassDifferentialFuzzTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/class-differential-fuzz.json)
muffin_add_test(NAME MuffinMermaidClassLayoutOracleTest SOURCE tests/mermaid/MermaidClassLayoutOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/class-layout.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassSceneOracleTest SOURCE tests/mermaid/MermaidClassSceneOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/class-layout.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassLinkStyleTest SOURCE tests/mermaid/MermaidClassLinkStyleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassGeometryOracleTest SOURCE tests/mermaid/MermaidClassGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/class-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidRequirementGeometryOracleTest SOURCE tests/mermaid/MermaidRequirementGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/requirement-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidRequirementPixelTest SOURCE tests/mermaid/MermaidRequirementPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/requirement-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidRequirementParserTest SOURCE tests/mermaid/MermaidRequirementParserTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinMermaidRequirementStyleTest SOURCE tests/mermaid/MermaidRequirementStyleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidRequirementTextStyleTest SOURCE tests/mermaid/MermaidRequirementTextStyleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidRequirementColorIndexTest SOURCE tests/mermaid/MermaidRequirementColorIndexTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidPieParserTest SOURCE tests/mermaid/MermaidPieParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/pie-grammar.json)
muffin_add_test(NAME MuffinMermaidPieGeometryOracleTest SOURCE tests/mermaid/MermaidPieGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/pie-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidPiePixelTest SOURCE tests/mermaid/MermaidPiePixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/pie-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidPieThemeWiringTest SOURCE tests/mermaid/MermaidPieThemeWiringTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidQuadrantParserTest SOURCE tests/mermaid/MermaidQuadrantParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/quadrant-grammar.json)
muffin_add_test(NAME MuffinMermaidQuadrantGeometryOracleTest SOURCE tests/mermaid/MermaidQuadrantGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/quadrant-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidQuadrantPixelTest SOURCE tests/mermaid/MermaidQuadrantPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/quadrant-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidQuadrantThemeWiringTest SOURCE tests/mermaid/MermaidQuadrantThemeWiringTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidJourneyParserTest SOURCE tests/mermaid/MermaidJourneyParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/journey-grammar.json)
muffin_add_test(NAME MuffinMermaidJourneyGeometryOracleTest SOURCE tests/mermaid/MermaidJourneyGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/journey-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidJourneyPixelTest SOURCE tests/mermaid/MermaidJourneyPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/journey-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidJourneyEdgeParityTest SOURCE tests/mermaid/MermaidJourneyEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidRadarParserTest SOURCE tests/mermaid/MermaidRadarParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/radar-grammar.json)
muffin_add_test(NAME MuffinMermaidRadarGeometryOracleTest SOURCE tests/mermaid/MermaidRadarGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/radar-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidRadarPixelTest SOURCE tests/mermaid/MermaidRadarPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/radar-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidRadarEdgeParityTest SOURCE tests/mermaid/MermaidRadarEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/radar-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidXYChartParserTest SOURCE tests/mermaid/MermaidXYChartParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/xychart-grammar.json)
muffin_add_test(NAME MuffinMermaidXYChartGeometryOracleTest SOURCE tests/mermaid/MermaidXYChartGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/xychart-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidXYChartPixelTest SOURCE tests/mermaid/MermaidXYChartPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/xychart-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidXYChartEdgeParityTest SOURCE tests/mermaid/MermaidXYChartEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/xychart-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidTimelineParserTest SOURCE tests/mermaid/MermaidTimelineParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/timeline-grammar.json)
muffin_add_test(NAME MuffinMermaidTimelineGeometryOracleTest SOURCE tests/mermaid/MermaidTimelineGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/timeline-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidTimelinePixelTest SOURCE tests/mermaid/MermaidTimelinePixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/timeline-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidTimelineEdgeParityTest SOURCE tests/mermaid/MermaidTimelineEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/timeline-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidPacketParserTest SOURCE tests/mermaid/MermaidPacketParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/packet-grammar.json)
muffin_add_test(NAME MuffinMermaidPacketGeometryOracleTest SOURCE tests/mermaid/MermaidPacketGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/packet-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidPacketPixelTest SOURCE tests/mermaid/MermaidPacketPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/packet-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidPacketEdgeParityTest SOURCE tests/mermaid/MermaidPacketEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/packet-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidKanbanParserTest SOURCE tests/mermaid/MermaidKanbanParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/kanban-grammar.json)
muffin_add_test(NAME MuffinMermaidKanbanGeometryOracleTest SOURCE tests/mermaid/MermaidKanbanGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/kanban-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidKanbanPixelTest SOURCE tests/mermaid/MermaidKanbanPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/kanban-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidKanbanEdgeParityTest SOURCE tests/mermaid/MermaidKanbanEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/kanban-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidMindmapParserTest SOURCE tests/mermaid/MermaidMindmapParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/mindmap-grammar.json)
muffin_add_test(NAME MuffinMermaidMindmapGeometryOracleTest SOURCE tests/mermaid/MermaidMindmapGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/mindmap-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidMindmapPixelTest SOURCE tests/mermaid/MermaidMindmapPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/mindmap-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidMindmapEdgeParityTest SOURCE tests/mermaid/MermaidMindmapEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/mindmap-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidGanttParserTest SOURCE tests/mermaid/MermaidGanttParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/gantt-grammar.json)
muffin_add_test(NAME MuffinMermaidGanttGeometryOracleTest SOURCE tests/mermaid/MermaidGanttGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/gantt-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidGanttPixelTest SOURCE tests/mermaid/MermaidGanttPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/gantt-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidGanttEdgeParityTest SOURCE tests/mermaid/MermaidGanttEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/gantt-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidInfoParserTest SOURCE tests/mermaid/MermaidInfoParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/info-grammar.json)
muffin_add_test(NAME MuffinMermaidInfoGeometryOracleTest SOURCE tests/mermaid/MermaidInfoGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/info-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidInfoPixelTest SOURCE tests/mermaid/MermaidInfoPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/info-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidInfoEdgeParityTest SOURCE tests/mermaid/MermaidInfoEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidTreeViewParserTest SOURCE tests/mermaid/MermaidTreeViewParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/treeview-grammar.json)
muffin_add_test(NAME MuffinMermaidTreeViewGeometryOracleTest SOURCE tests/mermaid/MermaidTreeViewGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/treeview-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidTreeViewEdgeParityTest SOURCE tests/mermaid/MermaidTreeViewEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/treeview-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidTreeViewPixelTest SOURCE tests/mermaid/MermaidTreeViewPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/treeview-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidEventModelingParserTest SOURCE tests/mermaid/MermaidEventModelingParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/eventmodeling-grammar.json)
muffin_add_test(NAME MuffinMermaidEventModelingGeometryOracleTest SOURCE tests/mermaid/MermaidEventModelingGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/eventmodeling-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidEventModelingPixelTest SOURCE tests/mermaid/MermaidEventModelingPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/eventmodeling-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidEventModelingEdgeParityTest SOURCE tests/mermaid/MermaidEventModelingEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/eventmodeling-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidIshikawaParserTest SOURCE tests/mermaid/MermaidIshikawaParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/ishikawa-grammar.json)
muffin_add_test(NAME MuffinMermaidIshikawaGeometryOracleTest SOURCE tests/mermaid/MermaidIshikawaGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/ishikawa-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidIshikawaPixelTest SOURCE tests/mermaid/MermaidIshikawaPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/ishikawa-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidIshikawaEdgeParityTest SOURCE tests/mermaid/MermaidIshikawaEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/ishikawa-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidVennParserTest SOURCE tests/mermaid/MermaidVennParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/venn-grammar.json)
muffin_add_test(NAME MuffinMermaidVennLayoutTest SOURCE tests/mermaid/MermaidVennLayoutTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/venn-geometry.json)
muffin_add_test(NAME MuffinMermaidVennGeometryOracleTest SOURCE tests/mermaid/MermaidVennGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/venn-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidVennPixelTest SOURCE tests/mermaid/MermaidVennPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/venn-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidVennEdgeParityTest SOURCE tests/mermaid/MermaidVennEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/venn-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSankeyParserTest SOURCE tests/mermaid/MermaidSankeyParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/sankey-grammar.json)
muffin_add_test(NAME MuffinMermaidSankeyGeometryOracleTest SOURCE tests/mermaid/MermaidSankeyGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sankey-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSankeyPixelTest SOURCE tests/mermaid/MermaidSankeyPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sankey-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSankeyEdgeParityTest SOURCE tests/mermaid/MermaidSankeyEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sankey-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidTreemapParserTest SOURCE tests/mermaid/MermaidTreemapParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/treemap-grammar.json)
muffin_add_test(NAME MuffinMermaidTreemapGeometryOracleTest SOURCE tests/mermaid/MermaidTreemapGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/treemap-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidTreemapPixelTest SOURCE tests/mermaid/MermaidTreemapPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/treemap-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidTreemapEdgeParityTest SOURCE tests/mermaid/MermaidTreemapEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/treemap-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidCynefinParserTest SOURCE tests/mermaid/MermaidCynefinParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/cynefin-grammar.json)
muffin_add_test(NAME MuffinMermaidCynefinGeometryOracleTest SOURCE tests/mermaid/MermaidCynefinGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/cynefin-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidCynefinPixelTest SOURCE tests/mermaid/MermaidCynefinPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/cynefin-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidCynefinEdgeParityTest SOURCE tests/mermaid/MermaidCynefinEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/cynefin-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidWardleyParserTest SOURCE tests/mermaid/MermaidWardleyParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/wardley-grammar.json)
muffin_add_test(NAME MuffinMermaidWardleyGeometryOracleTest SOURCE tests/mermaid/MermaidWardleyGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/wardley-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidWardleyPixelTest SOURCE tests/mermaid/MermaidWardleyPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/wardley-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidWardleyEdgeParityTest SOURCE tests/mermaid/MermaidWardleyEdgeParityTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/wardley-config.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidStateGeometryOracleTest SOURCE tests/mermaid/MermaidStateGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/state-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSequenceGeometryOracleTest SOURCE tests/mermaid/MermaidSequenceGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sequence-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidErSceneRegressionTest SOURCE tests/mermaid/MermaidErSceneRegressionTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/er-scene.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidErGeometryOracleTest SOURCE tests/mermaid/MermaidErGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/er-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidErStyleTest SOURCE tests/mermaid/MermaidErStyleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassPixelTest SOURCE tests/mermaid/MermaidClassPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/class-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassSvgStructuralTest SOURCE tests/mermaid/MermaidClassSvgStructuralTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/class-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassCoverageMatrixTest SOURCE tests/mermaid/MermaidClassCoverageMatrixTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/class-db.json)
muffin_add_test(NAME MuffinMermaidSequenceDifferentialFuzzTest SOURCE tests/mermaid/MermaidSequenceDifferentialFuzzTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/sequence-differential-fuzz.json)
muffin_add_test(NAME MuffinMermaidSequenceLayoutOracleTest SOURCE tests/mermaid/MermaidSequenceLayoutOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sequence-layout.json)
muffin_add_test(NAME MuffinMermaidSequenceLabelOracleTest SOURCE tests/mermaid/MermaidSequenceLabelOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sequence-label.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidMathFontContractTest SOURCE tests/mermaid/MermaidMathFontContractTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidMathMlCssBoxTest SOURCE tests/mermaid/MermaidMathMlCssBoxTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/mathml-css-box.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidMathMlOperationFuzzTest SOURCE tests/mermaid/MermaidMathMlOperationFuzzTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSequenceMathCacheTest SOURCE tests/mermaid/MermaidSequenceMathCacheTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
set_tests_properties(MuffinMermaidMathMlOperationFuzzTest MuffinMermaidSequenceMathCacheTest
    PROPERTIES RUN_SERIAL TRUE)
set_tests_properties(MuffinMermaidMathFontContractTest MuffinMermaidMathMlCssBoxTest MuffinMermaidMathMlOperationFuzzTest
    PROPERTIES LABELS "mermaid;math-font-oracle")
muffin_add_test(NAME MuffinMermaidSequencePixelTest SOURCE tests/mermaid/MermaidSequencePixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sequence-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSequenceSvgStructuralTest SOURCE tests/mermaid/MermaidSequenceSvgStructuralTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sequence-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSequenceAlignTest SOURCE tests/mermaid/MermaidSequenceAlignTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowLabelWeightTest SOURCE tests/mermaid/MermaidFlowLabelWeightTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowLabelTypographyTest SOURCE tests/mermaid/MermaidFlowLabelTypographyTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSequenceWeightTest SOURCE tests/mermaid/MermaidSequenceWeightTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSequenceCoverageMatrixTest SOURCE tests/mermaid/MermaidSequenceCoverageMatrixTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/sequence-db.json)
muffin_add_test(NAME MuffinMermaidDagreCompoundTest SOURCE tests/mermaid/MermaidDagreCompoundTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinParserBasicTest      SOURCE tests/parser/ParserBasicTest.cpp      LINK MuffinCore)
muffin_add_test(NAME MuffinParserDefinitionTest SOURCE tests/parser/ParserDefinitionTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinParserMathCodeTest   SOURCE tests/parser/ParserMathCodeTest.cpp   LINK MuffinCore)
muffin_add_test(NAME MuffinPieceTableTest       SOURCE tests/document/PieceTableTest.cpp     LINK MuffinCore)
muffin_add_test(NAME MuffinTextStatsTest        SOURCE tests/document/TextStatsTest.cpp      LINK MuffinCore)
muffin_add_test(NAME MuffinInlineTextSharingTest SOURCE tests/document/InlineTextSharingTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinRelativeOffsetTest   SOURCE tests/parser/RelativeOffsetTest.cpp   LINK MuffinCore)
muffin_add_test(NAME MuffinRelativeOffsetOracleTest SOURCE tests/parser/RelativeOffsetOracleTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinOutlineBuilderTest   SOURCE tests/document/OutlineBuilderTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinOutlineModelTest     SOURCE tests/app/OutlineModelTest.cpp         LINK MuffinUi)
muffin_add_test(NAME MuffinImageSyntaxOpsTest   SOURCE tests/document/ImageSyntaxOpsTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinFilePathOpsLinkTest  SOURCE tests/io/FilePathOpsLinkTest.cpp     LINK MuffinUi)
muffin_add_test(NAME MuffinFilePathOpsRenameTest SOURCE tests/io/FilePathOpsRenameTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinFileControllerFormatTest SOURCE tests/io/FileControllerFormatTest.cpp LINK MuffinUi EXTRA_SOURCES src/io/FileController.cpp RESOURCE_LOCK)
muffin_add_test(NAME MuffinMarkdownParseOptionsTest SOURCE tests/document/MarkdownParseOptionsTest.cpp EXTRA_SOURCES src/app/MarkdownSettings.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinAlertBoxParseTest       SOURCE tests/document/AlertBoxParseTest.cpp       LINK MuffinCore)
muffin_add_test(NAME MuffinHighlightParseTest      SOURCE tests/document/HighlightParseTest.cpp      LINK MuffinCore)
muffin_add_test(NAME MuffinSubscriptSuperscriptParseTest SOURCE tests/document/SubscriptSuperscriptParseTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinDraftRecoveryTest SOURCE tests/app/DraftRecoveryTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinDocumentSessionAsyncParseTest SOURCE tests/document/DocumentSessionAsyncParseTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinDocumentSessionFileWatchTest SOURCE tests/document/DocumentSessionFileWatchTest.cpp LINK MuffinCore)

# --- render (link MuffinUi, take the render_smoke fixture, lock the GUI) ---
muffin_add_test(NAME MuffinRenderThemeTest            SOURCE tests/render/RenderThemeTest.cpp            LINK MuffinUi EXTRA_SOURCES src/themes.qrc FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderIncrementalTest      SOURCE tests/render/RenderIncrementalTest.cpp      LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderListMarkerTest       SOURCE tests/render/RenderListMarkerTest.cpp       LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderInlineProjectionTest SOURCE tests/render/RenderInlineProjectionTest.cpp LINK MuffinUi EXTRA_SOURCES ${MUFFIN_EMOJI_QRC} FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderInlineGeometryTest   SOURCE tests/render/RenderInlineGeometryTest.cpp   LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderInlineHitTestTest    SOURCE tests/render/RenderInlineHitTest.cpp        LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderMathLayoutTest       SOURCE tests/render/RenderMathLayoutTest.cpp       LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderMathGeometryTest     SOURCE tests/render/RenderMathGeometryTest.cpp     LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderMathAuditTest        SOURCE tests/render/RenderMathAuditTest.cpp        LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderMathFunctions1Test   SOURCE tests/render/RenderMathFunctions1Test.cpp   LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderMathFunctions2Test   SOURCE tests/render/RenderMathFunctions2Test.cpp   LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderHtmlLayoutTest       SOURCE tests/render/RenderHtmlLayoutTest.cpp       LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderHtmlPaintTest        SOURCE tests/render/RenderHtmlPaintTest.cpp        LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderTreeSitterTest       SOURCE tests/render/RenderTreeSitterTest.cpp       LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderHeadingFitContentTest SOURCE tests/render/RenderHeadingFitContentTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderHeadingPseudoTest SOURCE tests/render/RenderHeadingPseudoTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderHeadingCounterTest SOURCE tests/render/HeadingCounterTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderTableOfContentsTest SOURCE tests/render/TableOfContentsTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderTableBackgroundTest SOURCE tests/render/TableBackgroundTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderHeadingPillTest SOURCE tests/render/RenderHeadingPillTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderLetterSpacingTest SOURCE tests/render/RenderLetterSpacingTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderInlineCodeBoxTest SOURCE tests/render/RenderInlineCodeBoxTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderImageDataUriTest SOURCE tests/render/RenderImageDataUriTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderLinkBeforeFlowTest SOURCE tests/render/RenderLinkBeforeFlowTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderMathLineHeightTest SOURCE tests/render/RenderMathLineHeightTest.cpp LINK MuffinUi RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderMathLinkBeforeOffsetTest SOURCE tests/render/RenderMathLinkBeforeOffsetTest.cpp LINK MuffinUi RESOURCE_LOCK DISABLED_ON APPLE)

# --- export (link MuffinUi; pure logic under QCoreApplication, no GUI lock) ---
muffin_add_test(NAME MuffinHtmlExporterTest   SOURCE tests/export/HtmlExporterTest.cpp   LINK MuffinUi)
muffin_add_test(NAME MuffinPandocRunnerTest   SOURCE tests/export/PandocRunnerTest.cpp   LINK MuffinUi)
muffin_add_test(NAME MuffinMarkdownHtmlSerializerTest SOURCE tests/projection/MarkdownHtmlSerializerTest.cpp LINK MuffinUi EXTRA_SOURCES ${MUFFIN_EMOJI_QRC} RESOURCE_LOCK)

# --- theme CSS mapper (link MuffinUi; pure logic under QCoreApplication, no GUI lock) ---
muffin_add_test(NAME MuffinCssComputedStyleEngineTest SOURCE tests/theme/CssComputedStyleEngineTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinCssThemeMapperTest SOURCE tests/theme/CssThemeMapperTest.cpp LINK MuffinUi EXTRA_SOURCES src/themes.qrc FIXTURE tests/fixtures/theme/mist-blue.css)
muffin_add_test(NAME MuffinThemeAccessibilityTest SOURCE tests/theme/ThemeAccessibilityTest.cpp LINK MuffinUi EXTRA_SOURCES src/themes.qrc)

# --- image subsystem (link MuffinUi; pure logic under QCoreApplication, no GUI lock) ---
muffin_add_test(NAME MuffinImageInsertionPolicyTest  SOURCE tests/image/ImageInsertionPolicyTest.cpp  LINK MuffinUi)
muffin_add_test(NAME MuffinImageFileOpsMoveTest       SOURCE tests/image/ImageFileOpsMoveTest.cpp       LINK MuffinUi)
muffin_add_test(NAME MuffinCustomCommandUploaderTest SOURCE tests/image/CustomCommandUploaderTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinImageDecoderTest          SOURCE tests/image/ImageDecoderTest.cpp          LINK MuffinUi)

# --- editor view (link MuffinUi, lock the GUI; no fixture arg) ---
muffin_add_test(NAME MuffinEditorViewProjectionSourceTest SOURCE tests/render/EditorViewProjectionSourceTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorViewProjectionMappingTest SOURCE tests/render/EditorViewProjectionMappingTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorViewHitTestTest    SOURCE tests/render/EditorViewHitTestTest.cpp    LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorViewTaskCheckboxTest SOURCE tests/render/EditorViewTaskCheckboxTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorViewSelectionTest  SOURCE tests/render/EditorViewSelectionTest.cpp  LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorViewLayoutTest     SOURCE tests/render/EditorViewLayoutTest.cpp     LINK MuffinUi RESOURCE_LOCK)

# --- editor input / controller ---
muffin_add_test(NAME MuffinEditorCoreTest              SOURCE tests/editor/EditorCoreTest.cpp              LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinSourceLineHeightIndexTest   SOURCE tests/editor/SourceLineHeightIndexTest.cpp   LINK MuffinUi)
muffin_add_test(NAME MuffinImageResizeTest             SOURCE tests/editor/ImageResizeTest.cpp            LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorStyleClipboardTest    SOURCE tests/editor/EditorStyleClipboardTest.cpp    LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorCodeFenceSelectionTest SOURCE tests/editor/EditorCodeFenceSelectionTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputTextEditingTest        SOURCE tests/editor/InputTextEditingTest.cpp        LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputParagraphTest          SOURCE tests/editor/InputParagraphTest.cpp          LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputUndoSelectionTest      SOURCE tests/editor/InputUndoSelectionTest.cpp      LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputListTabTest            SOURCE tests/editor/InputListTabTest.cpp            LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputIndentSizeTest         SOURCE tests/editor/InputIndentSizeTest.cpp         LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputMarkdownDefaultsTest   SOURCE tests/editor/InputMarkdownDefaultsTest.cpp   LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputShiftTabDedentTest     SOURCE tests/editor/InputShiftTabDedentTest.cpp     LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputAlignIndentTest        SOURCE tests/editor/InputAlignIndentTest.cpp        LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputAutoPairTest           SOURCE tests/editor/InputAutoPairTest.cpp          LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEmojiTriggerTest            SOURCE tests/editor/EmojiTriggerTest.cpp           LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinOrderedListMarkerCursorTest SOURCE tests/editor/OrderedListMarkerCursorTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputLazyBlockTest          SOURCE tests/editor/InputLazyBlockTest.cpp          LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinBackspaceEmptyListItemTest  SOURCE tests/editor/BackspaceEmptyListItemTest.cpp  LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinBackspaceTrailingCaretTest  SOURCE tests/editor/BackspaceTrailingCaretTest.cpp  LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinThematicBreakEditTest       SOURCE tests/editor/ThematicBreakEditTest.cpp       LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinBackspaceEmptyParagraphTest SOURCE tests/editor/BackspaceEmptyParagraphTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputDeleteRangeTest        SOURCE tests/editor/InputDeleteRangeTest.cpp        LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinSourceEditorBackendDeleteTest SOURCE tests/app/SourceEditorBackendDeleteTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinDocumentSearchTest             SOURCE tests/editor/DocumentSearchTest.cpp       LINK MuffinUi)
muffin_add_test(NAME MuffinInputLiteralMergeTest       SOURCE tests/editor/InputLiteralMergeTest.cpp       LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinCodeFenceCommitCursorTest   SOURCE tests/editor/CodeFenceCommitCursorTest.cpp   LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputBlockEditingTest       SOURCE tests/editor/InputBlockEditingTest.cpp       LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputBlockquoteTypingTest   SOURCE tests/editor/InputBlockquoteTypingTest.cpp   LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputDefinitionHeadingTest  SOURCE tests/editor/InputDefinitionHeadingTest.cpp  LINK MuffinUi RESOURCE_LOCK)

# --- block commands ---
muffin_add_test(NAME MuffinParagraphHeadingTest     SOURCE tests/commands/ParagraphHeadingTest.cpp     LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinParagraphBlockInsertTest SOURCE tests/commands/ParagraphBlockInsertTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinParagraphMarkdownDefaultsTest SOURCE tests/commands/ParagraphMarkdownDefaultsTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinParagraphToggleBlockTest SOURCE tests/commands/ParagraphToggleBlockTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinParagraphToggleUndoTest  SOURCE tests/commands/ParagraphToggleUndoTest.cpp  LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinParagraphTaskToggleTest  SOURCE tests/commands/ParagraphTaskToggleTest.cpp  LINK MuffinUi RESOURCE_LOCK)

# --- blocks / controllers (pure-logic controller tests link MuffinUi but never spin up a GUI,
#     so they omit RESOURCE_LOCK and stay parallel; the two that do render take the lock) ---
muffin_add_test(NAME MuffinTableModelOpsTest       SOURCE tests/blocks/TableModelOpsTest.cpp       LINK MuffinUi)
muffin_add_test(NAME MuffinTableControllerTest     SOURCE tests/blocks/TableControllerTest.cpp     LINK MuffinUi)
muffin_add_test(NAME MuffinTableCellEditingTest    SOURCE tests/blocks/TableCellEditingTest.cpp    LINK MuffinUi)
muffin_add_test(NAME MuffinCodeFenceControllerTest SOURCE tests/blocks/CodeFenceControllerTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinCodeFenceScrollControllerTest SOURCE tests/blocks/CodeFenceScrollControllerTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinMathBlockControllerTest SOURCE tests/blocks/MathBlockControllerTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinHtmlBlockControllerTest SOURCE tests/blocks/HtmlBlockControllerTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinHtmlSanitizerTest       SOURCE tests/blocks/HtmlSanitizerTest.cpp       LINK MuffinUi)
muffin_add_test(NAME MuffinBlockTableUndoTest      SOURCE tests/blocks/BlockTableUndoTest.cpp      LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinBlockCodeFrontMatterTest SOURCE tests/blocks/BlockCodeFrontMatterTest.cpp LINK MuffinUi RESOURCE_LOCK)

# --- app ---
muffin_add_test(NAME MuffinTranslationResourceTest SOURCE tests/app/TranslationResourceTest.cpp LINK Qt6::Widgets EXTRA_SOURCES src/translations.qrc RESOURCE_LOCK)

# --- spell check (needs the bundled dictionaries, hence dicts.qrc as an extra source) ---
muffin_add_test(NAME MuffinSpellCheckerTest SOURCE tests/spellcheck/SpellCheckerTest.cpp LINK MuffinUi EXTRA_SOURCES ${MUFFIN_DICTS_QRC} RESOURCE_LOCK)
