# All Muffin test executables, registered via muffin_add_test (see MuffinTestFunctions.cmake).
# One line per test; grouped by subsystem in build order. Included from the top-level
# CMakeLists.txt after MUFFIN_TEST_ENVIRONMENT_MODIFICATIONS is assembled.

include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/MuffinTestFunctions.cmake)

# --- perf benchmark (pure MuffinCore, no GUI lock; defaults are a fast smoke — override
#     MUFFIN_BENCH_SIZE_MB / MUFFIN_BENCH_ITERS for a real measurement run) ---
muffin_add_test(NAME MuffinTypingPerfBench SOURCE tests/perf/TypingPerfBench.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinOpenMemBench SOURCE tests/perf/OpenMemBench.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinOpenRenderMemBench SOURCE tests/perf/OpenRenderMemBench.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinLargeDocumentRoundTripTest SOURCE tests/perf/LargeDocumentRoundTripTest.cpp LINK MuffinUi EXTRA_SOURCES src/io/FileController.cpp RESOURCE_LOCK)
muffin_add_test(NAME MuffinThirdDashProbe SOURCE tests/perf/ThirdDashProbe.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinSplitAfterRuleProbe SOURCE tests/perf/SplitAfterRuleProbe.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinThematicBreakRangeProbe SOURCE tests/perf/ThematicBreakRangeProbe.cpp LINK MuffinUi RESOURCE_LOCK)

# --- parser / document (pure logic; link MuffinCore, no Qt GUI lock) ---
muffin_add_test(NAME MuffinMermaidCompatibilityTest SOURCE tests/mermaid/MermaidCompatibilityTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/preprocess-and-detect.json)
muffin_add_test(NAME MuffinMermaidFlowchartParserTest SOURCE tests/mermaid/MermaidFlowchartParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/flowchart-db.json)
muffin_add_test(NAME MuffinMermaidFlowchartDifferentialFuzzTest SOURCE tests/mermaid/MermaidFlowchartDifferentialFuzzTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/flowchart-differential-fuzz.json)
muffin_add_test(NAME MuffinMermaidParserErrorTest SOURCE tests/mermaid/MermaidParserErrorTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/flowchart-errors.json)
muffin_add_test(NAME MuffinMermaidSecurityTest SOURCE tests/mermaid/MermaidSecurityTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinMermaidFuzzTest SOURCE tests/mermaid/MermaidFuzzTest.cpp LINK MuffinCore)
set_tests_properties(MuffinMermaidFuzzTest PROPERTIES RUN_SERIAL TRUE)
muffin_add_test(NAME MuffinMermaidRenderCacheTest SOURCE tests/mermaid/MermaidRenderCacheTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSvgExportTest SOURCE tests/mermaid/MermaidSvgExportTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui Qt6::Svg RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidConfigEffectMatrixTest SOURCE tests/mermaid/MermaidConfigEffectMatrixTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/config-effect-matrix.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSceneCullingTest SOURCE tests/mermaid/MermaidSceneCullingTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderMermaidBlockTest SOURCE tests/render/RenderMermaidBlockTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowchartLayoutTest SOURCE tests/mermaid/MermaidFlowchartLayoutTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidDagreLayoutTest SOURCE tests/mermaid/MermaidDagreLayoutTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidDagreSnapshotTest SOURCE tests/mermaid/MermaidDagreSnapshotTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-geometry.json RESOURCE_LOCK)
# MuffinMermaidDagreLayoutTest (tests/mermaid/MermaidDagreLayoutTest.cpp) is the
# milestone-C acceptance gate for layoutFlowchartNodesDagre; temporarily
# registered while debugging the remaining cases (compound-crossing mirror,
# self-edge). Skips compound-crossing via pendingNative.
muffin_add_test(NAME MuffinMermaidGraphTest SOURCE tests/mermaid/MermaidGraphTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinMermaidShapeRegistryTest SOURCE tests/mermaid/MermaidShapeRegistryTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinMermaidThemeTest SOURCE tests/mermaid/MermaidThemeTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-theme.json)
muffin_add_test(NAME MuffinMermaidFlowStyleResolveTest SOURCE tests/mermaid/MermaidFlowStyleResolveTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-style-cascade.json)
muffin_add_test(NAME MuffinMermaidFlowchartSceneTest SOURCE tests/mermaid/MermaidFlowchartSceneTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-scene.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowchartAnimationTest SOURCE tests/mermaid/MermaidFlowchartAnimationTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidGoldenPixelTest SOURCE tests/mermaid/MermaidGoldenPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/golden-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowchartSvgStructuralTest SOURCE tests/mermaid/MermaidFlowchartSvgStructuralTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/golden-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowchartLabelOracleTest SOURCE tests/mermaid/MermaidFlowchartLabelOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/flowchart-label.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidFlowchartCoverageMatrixTest SOURCE tests/mermaid/MermaidFlowchartCoverageMatrixTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/flowchart-db.json)
muffin_add_test(NAME MuffinMermaidTextLayoutAuditTest SOURCE tests/mermaid/MermaidTextLayoutAuditTest.cpp LINK MuffinCore FIXTURE src/mermaid/flowchart/FlowLabel.cpp)
muffin_add_test(NAME MuffinMermaidRoughOpsTest SOURCE tests/mermaid/MermaidRoughOpsTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/rough-ops.json)
muffin_add_test(NAME MuffinMermaidSequenceParserTest SOURCE tests/mermaid/MermaidSequenceParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/sequence-db.json)
muffin_add_test(NAME MuffinMermaidClassParserTest SOURCE tests/mermaid/MermaidClassParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/class-db.json)
muffin_add_test(NAME MuffinMermaidErParserTest SOURCE tests/mermaid/MermaidErParserTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/er-db.json)
muffin_add_test(NAME MuffinMermaidStateUpstreamContractTest SOURCE tests/mermaid/MermaidStateUpstreamContractTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/state-db.json)
muffin_add_test(NAME MuffinMermaidStateDifferentialFuzzTest SOURCE tests/mermaid/MermaidStateDifferentialFuzzTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/state-differential-fuzz.json)
muffin_add_test(NAME MuffinMermaidStateSceneTest SOURCE tests/mermaid/MermaidStateSceneTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/state-db.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidStateLayoutOracleTest SOURCE tests/mermaid/MermaidStateLayoutOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/state-layout.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidStateSvgStructuralTest SOURCE tests/mermaid/MermaidStateSvgStructuralTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/state-layout.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidStatePixelTest SOURCE tests/mermaid/MermaidStatePixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/state-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassDifferentialFuzzTest SOURCE tests/mermaid/MermaidClassDifferentialFuzzTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/class-differential-fuzz.json)
muffin_add_test(NAME MuffinMermaidClassLayoutOracleTest SOURCE tests/mermaid/MermaidClassLayoutOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/class-layout.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassSceneOracleTest SOURCE tests/mermaid/MermaidClassSceneOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/class-layout.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidErSceneRegressionTest SOURCE tests/mermaid/MermaidErSceneRegressionTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/er-scene.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidErGeometryOracleTest SOURCE tests/mermaid/MermaidErGeometryOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/er-geometry.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassPixelTest SOURCE tests/mermaid/MermaidClassPixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/class-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassSvgStructuralTest SOURCE tests/mermaid/MermaidClassSvgStructuralTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/class-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidClassCoverageMatrixTest SOURCE tests/mermaid/MermaidClassCoverageMatrixTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/class-db.json)
muffin_add_test(NAME MuffinMermaidSequenceDifferentialFuzzTest SOURCE tests/mermaid/MermaidSequenceDifferentialFuzzTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/sequence-differential-fuzz.json)
muffin_add_test(NAME MuffinMermaidSequenceLayoutOracleTest SOURCE tests/mermaid/MermaidSequenceLayoutOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sequence-layout.json)
muffin_add_test(NAME MuffinMermaidSequenceLabelOracleTest SOURCE tests/mermaid/MermaidSequenceLabelOracleTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sequence-label.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidMathFontContractTest SOURCE tests/mermaid/MermaidMathFontContractTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidMathMlCssBoxTest SOURCE tests/mermaid/MermaidMathMlCssBoxTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/mathml-css-box.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidMathMlOperationFuzzTest SOURCE tests/mermaid/MermaidMathMlOperationFuzzTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSequenceMathCacheTest SOURCE tests/mermaid/MermaidSequenceMathCacheTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui RESOURCE_LOCK)
set_tests_properties(MuffinMermaidMathMlOperationFuzzTest MuffinMermaidSequenceMathCacheTest
    PROPERTIES RUN_SERIAL TRUE)
set_tests_properties(MuffinMermaidMathFontContractTest MuffinMermaidMathMlCssBoxTest MuffinMermaidMathMlOperationFuzzTest
    PROPERTIES LABELS "mermaid;math-font-oracle")
muffin_add_test(NAME MuffinMermaidSequencePixelTest SOURCE tests/mermaid/MermaidSequencePixelTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sequence-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSequenceSvgStructuralTest SOURCE tests/mermaid/MermaidSequenceSvgStructuralTest.cpp LINK MuffinCore EXTRA_LINK Qt6::Gui FIXTURE tests/fixtures/mermaid/sequence-pixel/manifest.json RESOURCE_LOCK)
muffin_add_test(NAME MuffinMermaidSequenceCoverageMatrixTest SOURCE tests/mermaid/MermaidSequenceCoverageMatrixTest.cpp LINK MuffinCore FIXTURE tests/fixtures/mermaid/sequence-db.json)
muffin_add_test(NAME MuffinMermaidDagreCompoundTest SOURCE tests/mermaid/MermaidDagreCompoundTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinParserBasicTest      SOURCE tests/parser/ParserBasicTest.cpp      LINK MuffinCore)
muffin_add_test(NAME MuffinParserDefinitionTest SOURCE tests/parser/ParserDefinitionTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinParserMathCodeTest   SOURCE tests/parser/ParserMathCodeTest.cpp   LINK MuffinCore)
muffin_add_test(NAME MuffinPieceTableTest       SOURCE tests/document/PieceTableTest.cpp     LINK MuffinCore)
muffin_add_test(NAME MuffinTextStatsTest        SOURCE tests/document/TextStatsTest.cpp      LINK MuffinCore)
muffin_add_test(NAME MuffinInlineTextSharingTest SOURCE tests/document/InlineTextSharingTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinRelativeOffsetTest   SOURCE tests/parser/RelativeOffsetTest.cpp   LINK MuffinCore)
muffin_add_test(NAME MuffinRelativeOffsetOracleTest SOURCE tests/parser/RelativeOffsetOracleTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinOutlineBuilderTest   SOURCE tests/document/OutlineBuilderTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinOutlineModelTest     SOURCE tests/app/OutlineModelTest.cpp         LINK MuffinUi)
muffin_add_test(NAME MuffinImageSyntaxOpsTest   SOURCE tests/document/ImageSyntaxOpsTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinFilePathOpsLinkTest  SOURCE tests/io/FilePathOpsLinkTest.cpp     LINK MuffinUi)
muffin_add_test(NAME MuffinFilePathOpsRenameTest SOURCE tests/io/FilePathOpsRenameTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinFileControllerFormatTest SOURCE tests/io/FileControllerFormatTest.cpp LINK MuffinUi EXTRA_SOURCES src/io/FileController.cpp RESOURCE_LOCK)
muffin_add_test(NAME MuffinMarkdownParseOptionsTest SOURCE tests/document/MarkdownParseOptionsTest.cpp EXTRA_SOURCES src/app/MarkdownSettings.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinAlertBoxParseTest       SOURCE tests/document/AlertBoxParseTest.cpp       LINK MuffinCore)
muffin_add_test(NAME MuffinHighlightParseTest      SOURCE tests/document/HighlightParseTest.cpp      LINK MuffinCore)
muffin_add_test(NAME MuffinSubscriptSuperscriptParseTest SOURCE tests/document/SubscriptSuperscriptParseTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinDraftRecoveryTest SOURCE tests/app/DraftRecoveryTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinDocumentSessionAsyncParseTest SOURCE tests/document/DocumentSessionAsyncParseTest.cpp LINK MuffinCore)
muffin_add_test(NAME MuffinDocumentSessionFileWatchTest SOURCE tests/document/DocumentSessionFileWatchTest.cpp LINK MuffinCore)

# --- render (link MuffinUi, take the render_smoke fixture, lock the GUI) ---
muffin_add_test(NAME MuffinRenderThemeTest            SOURCE tests/render/RenderThemeTest.cpp            LINK MuffinUi EXTRA_SOURCES src/themes.qrc FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderIncrementalTest      SOURCE tests/render/RenderIncrementalTest.cpp      LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderListMarkerTest       SOURCE tests/render/RenderListMarkerTest.cpp       LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderInlineProjectionTest SOURCE tests/render/RenderInlineProjectionTest.cpp LINK MuffinUi EXTRA_SOURCES ${MUFFIN_EMOJI_QRC} FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderInlineGeometryTest   SOURCE tests/render/RenderInlineGeometryTest.cpp   LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderInlineHitTestTest    SOURCE tests/render/RenderInlineHitTest.cpp        LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderMathLayoutTest       SOURCE tests/render/RenderMathLayoutTest.cpp       LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderMathGeometryTest     SOURCE tests/render/RenderMathGeometryTest.cpp     LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderMathAuditTest        SOURCE tests/render/RenderMathAuditTest.cpp        LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderMathFunctions1Test   SOURCE tests/render/RenderMathFunctions1Test.cpp   LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderMathFunctions2Test   SOURCE tests/render/RenderMathFunctions2Test.cpp   LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderHtmlLayoutTest       SOURCE tests/render/RenderHtmlLayoutTest.cpp       LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderHtmlPaintTest        SOURCE tests/render/RenderHtmlPaintTest.cpp        LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderTreeSitterTest       SOURCE tests/render/RenderTreeSitterTest.cpp       LINK MuffinUi FIXTURE tests/fixtures/render_smoke.md RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderHeadingFitContentTest SOURCE tests/render/RenderHeadingFitContentTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderHeadingPseudoTest SOURCE tests/render/RenderHeadingPseudoTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderHeadingCounterTest SOURCE tests/render/HeadingCounterTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderTableOfContentsTest SOURCE tests/render/TableOfContentsTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderTableBackgroundTest SOURCE tests/render/TableBackgroundTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderHeadingPillTest SOURCE tests/render/RenderHeadingPillTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderLetterSpacingTest SOURCE tests/render/RenderLetterSpacingTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderInlineCodeBoxTest SOURCE tests/render/RenderInlineCodeBoxTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderImageDataUriTest SOURCE tests/render/RenderImageDataUriTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderLinkBeforeFlowTest SOURCE tests/render/RenderLinkBeforeFlowTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinRenderMathLineHeightTest SOURCE tests/render/RenderMathLineHeightTest.cpp LINK MuffinUi RESOURCE_LOCK DISABLED_ON APPLE)
muffin_add_test(NAME MuffinRenderMathLinkBeforeOffsetTest SOURCE tests/render/RenderMathLinkBeforeOffsetTest.cpp LINK MuffinUi RESOURCE_LOCK DISABLED_ON APPLE)

# --- export (link MuffinUi; pure logic under QCoreApplication, no GUI lock) ---
muffin_add_test(NAME MuffinHtmlExporterTest   SOURCE tests/export/HtmlExporterTest.cpp   LINK MuffinUi)
muffin_add_test(NAME MuffinPandocRunnerTest   SOURCE tests/export/PandocRunnerTest.cpp   LINK MuffinUi)
muffin_add_test(NAME MuffinMarkdownHtmlSerializerTest SOURCE tests/projection/MarkdownHtmlSerializerTest.cpp LINK MuffinUi EXTRA_SOURCES ${MUFFIN_EMOJI_QRC} RESOURCE_LOCK)

# --- theme CSS mapper (link MuffinUi; pure logic under QCoreApplication, no GUI lock) ---
muffin_add_test(NAME MuffinCssComputedStyleEngineTest SOURCE tests/theme/CssComputedStyleEngineTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinCssThemeMapperTest SOURCE tests/theme/CssThemeMapperTest.cpp LINK MuffinUi EXTRA_SOURCES src/themes.qrc FIXTURE tests/fixtures/theme/mist-blue.css)
muffin_add_test(NAME MuffinThemeAccessibilityTest SOURCE tests/theme/ThemeAccessibilityTest.cpp LINK MuffinUi EXTRA_SOURCES src/themes.qrc)

# --- image subsystem (link MuffinUi; pure logic under QCoreApplication, no GUI lock) ---
muffin_add_test(NAME MuffinImageInsertionPolicyTest  SOURCE tests/image/ImageInsertionPolicyTest.cpp  LINK MuffinUi)
muffin_add_test(NAME MuffinImageFileOpsMoveTest       SOURCE tests/image/ImageFileOpsMoveTest.cpp       LINK MuffinUi)
muffin_add_test(NAME MuffinCustomCommandUploaderTest SOURCE tests/image/CustomCommandUploaderTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinImageDecoderTest          SOURCE tests/image/ImageDecoderTest.cpp          LINK MuffinUi)

# --- editor view (link MuffinUi, lock the GUI; no fixture arg) ---
muffin_add_test(NAME MuffinEditorViewProjectionSourceTest SOURCE tests/render/EditorViewProjectionSourceTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorViewProjectionMappingTest SOURCE tests/render/EditorViewProjectionMappingTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorViewHitTestTest    SOURCE tests/render/EditorViewHitTestTest.cpp    LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorViewTaskCheckboxTest SOURCE tests/render/EditorViewTaskCheckboxTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorViewSelectionTest  SOURCE tests/render/EditorViewSelectionTest.cpp  LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorViewLayoutTest     SOURCE tests/render/EditorViewLayoutTest.cpp     LINK MuffinUi RESOURCE_LOCK)

# --- editor input / controller ---
muffin_add_test(NAME MuffinEditorCoreTest              SOURCE tests/editor/EditorCoreTest.cpp              LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinSourceLineHeightIndexTest   SOURCE tests/editor/SourceLineHeightIndexTest.cpp   LINK MuffinUi)
muffin_add_test(NAME MuffinImageResizeTest             SOURCE tests/editor/ImageResizeTest.cpp            LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorStyleClipboardTest    SOURCE tests/editor/EditorStyleClipboardTest.cpp    LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEditorCodeFenceSelectionTest SOURCE tests/editor/EditorCodeFenceSelectionTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputTextEditingTest        SOURCE tests/editor/InputTextEditingTest.cpp        LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputParagraphTest          SOURCE tests/editor/InputParagraphTest.cpp          LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputUndoSelectionTest      SOURCE tests/editor/InputUndoSelectionTest.cpp      LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputListTabTest            SOURCE tests/editor/InputListTabTest.cpp            LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputIndentSizeTest         SOURCE tests/editor/InputIndentSizeTest.cpp         LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputMarkdownDefaultsTest   SOURCE tests/editor/InputMarkdownDefaultsTest.cpp   LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputShiftTabDedentTest     SOURCE tests/editor/InputShiftTabDedentTest.cpp     LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputAlignIndentTest        SOURCE tests/editor/InputAlignIndentTest.cpp        LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputAutoPairTest           SOURCE tests/editor/InputAutoPairTest.cpp          LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinEmojiTriggerTest            SOURCE tests/editor/EmojiTriggerTest.cpp           LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinOrderedListMarkerCursorTest SOURCE tests/editor/OrderedListMarkerCursorTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputLazyBlockTest          SOURCE tests/editor/InputLazyBlockTest.cpp          LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinBackspaceEmptyListItemTest  SOURCE tests/editor/BackspaceEmptyListItemTest.cpp  LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinBackspaceTrailingCaretTest  SOURCE tests/editor/BackspaceTrailingCaretTest.cpp  LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinThematicBreakEditTest       SOURCE tests/editor/ThematicBreakEditTest.cpp       LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinBackspaceEmptyParagraphTest SOURCE tests/editor/BackspaceEmptyParagraphTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputDeleteRangeTest        SOURCE tests/editor/InputDeleteRangeTest.cpp        LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinSourceEditorBackendDeleteTest SOURCE tests/app/SourceEditorBackendDeleteTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinDocumentSearchTest             SOURCE tests/editor/DocumentSearchTest.cpp       LINK MuffinUi)
muffin_add_test(NAME MuffinInputLiteralMergeTest       SOURCE tests/editor/InputLiteralMergeTest.cpp       LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinCodeFenceCommitCursorTest   SOURCE tests/editor/CodeFenceCommitCursorTest.cpp   LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputBlockEditingTest       SOURCE tests/editor/InputBlockEditingTest.cpp       LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputBlockquoteTypingTest   SOURCE tests/editor/InputBlockquoteTypingTest.cpp   LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinInputDefinitionHeadingTest  SOURCE tests/editor/InputDefinitionHeadingTest.cpp  LINK MuffinUi RESOURCE_LOCK)

# --- block commands ---
muffin_add_test(NAME MuffinParagraphHeadingTest     SOURCE tests/commands/ParagraphHeadingTest.cpp     LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinParagraphBlockInsertTest SOURCE tests/commands/ParagraphBlockInsertTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinParagraphMarkdownDefaultsTest SOURCE tests/commands/ParagraphMarkdownDefaultsTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinParagraphToggleBlockTest SOURCE tests/commands/ParagraphToggleBlockTest.cpp LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinParagraphToggleUndoTest  SOURCE tests/commands/ParagraphToggleUndoTest.cpp  LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinParagraphTaskToggleTest  SOURCE tests/commands/ParagraphTaskToggleTest.cpp  LINK MuffinUi RESOURCE_LOCK)

# --- blocks / controllers (pure-logic controller tests link MuffinUi but never spin up a GUI,
#     so they omit RESOURCE_LOCK and stay parallel; the two that do render take the lock) ---
muffin_add_test(NAME MuffinTableModelOpsTest       SOURCE tests/blocks/TableModelOpsTest.cpp       LINK MuffinUi)
muffin_add_test(NAME MuffinTableControllerTest     SOURCE tests/blocks/TableControllerTest.cpp     LINK MuffinUi)
muffin_add_test(NAME MuffinTableCellEditingTest    SOURCE tests/blocks/TableCellEditingTest.cpp    LINK MuffinUi)
muffin_add_test(NAME MuffinCodeFenceControllerTest SOURCE tests/blocks/CodeFenceControllerTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinCodeFenceScrollControllerTest SOURCE tests/blocks/CodeFenceScrollControllerTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinMathBlockControllerTest SOURCE tests/blocks/MathBlockControllerTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinHtmlBlockControllerTest SOURCE tests/blocks/HtmlBlockControllerTest.cpp LINK MuffinUi)
muffin_add_test(NAME MuffinHtmlSanitizerTest       SOURCE tests/blocks/HtmlSanitizerTest.cpp       LINK MuffinUi)
muffin_add_test(NAME MuffinBlockTableUndoTest      SOURCE tests/blocks/BlockTableUndoTest.cpp      LINK MuffinUi RESOURCE_LOCK)
muffin_add_test(NAME MuffinBlockCodeFrontMatterTest SOURCE tests/blocks/BlockCodeFrontMatterTest.cpp LINK MuffinUi RESOURCE_LOCK)

# --- app ---
muffin_add_test(NAME MuffinTranslationResourceTest SOURCE tests/app/TranslationResourceTest.cpp LINK Qt6::Widgets EXTRA_SOURCES src/translations.qrc RESOURCE_LOCK)

# --- spell check (needs the bundled dictionaries, hence dicts.qrc as an extra source) ---
muffin_add_test(NAME MuffinSpellCheckerTest SOURCE tests/spellcheck/SpellCheckerTest.cpp LINK MuffinUi EXTRA_SOURCES ${MUFFIN_DICTS_QRC} RESOURCE_LOCK)
